server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    username: user
    password: pass
    driver-class-name: org.h2.Driver

logging:
  level:
    root: INFO
    org.springframework.web: INFO